// Code generated by goctl. DO NOT EDIT.
// Source: bsllm.proto

package server

import (
	"context"

	"jxzy/bs/bs_llm/bs_llm"
	"jxzy/bs/bs_llm/internal/logic"
	"jxzy/bs/bs_llm/internal/svc"
)

type BsLlmServiceServer struct {
	svcCtx *svc.ServiceContext
	bs_llm.UnimplementedBsLlmServiceServer
}

func NewBsLlmServiceServer(svcCtx *svc.ServiceContext) *BsLlmServiceServer {
	return &BsLlmServiceServer{
		svcCtx: svcCtx,
	}
}

// 流式LLM调用
func (s *BsLlmServiceServer) StreamLLM(in *bs_llm.LLMRequest, stream bs_llm.BsLlmService_StreamLLMServer) error {
	l := logic.NewStreamLLMLogic(stream.Context(), s.svcCtx)
	return l.StreamLLM(in, stream)
}

// 非流式LLM调用
func (s *BsLlmServiceServer) LLM(ctx context.Context, in *bs_llm.LLMRequest) (*bs_llm.LLMResponse, error) {
	l := logic.NewLLMLogic(ctx, s.svcCtx)
	return l.LLM(in)
}
