// Code generated by goctl. DO NOT EDIT.
// Source: bllknowledge.proto

package bllknowledgeservice

import (
	"context"

	"jxzy/bll/bll_knowledge/bll_knowledge"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty = bll_knowledge.Empty
	Pong  = bll_knowledge.Pong

	BllKnowledgeService interface {
		// 占位方法，后续添加具体实现
		Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
	}

	defaultBllKnowledgeService struct {
		cli zrpc.Client
	}
)

func NewBllKnowledgeService(cli zrpc.Client) BllKnowledgeService {
	return &defaultBllKnowledgeService{
		cli: cli,
	}
}

// 占位方法，后续添加具体实现
func (m *defaultBllKnowledgeService) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	client := bll_knowledge.NewBllKnowledgeServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
