// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	knowledge "jxzy/apis/api_knowledge/internal/handler/knowledge"
	"jxzy/apis/api_knowledge/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: knowledge.AddKnowledgeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: knowledge.DeleteKnowledgeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/knowledge"),
	)
}
