// Code generated by goctl. DO NOT EDIT.
// Source: bllprompt.proto

package bllpromptservice

import (
	"context"

	"jxzy/bll/bll_prompt/bll_prompt"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty = bll_prompt.Empty
	Pong  = bll_prompt.Pong

	BllPromptService interface {
		// 占位方法，后续添加具体实现
		Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
	}

	defaultBllPromptService struct {
		cli zrpc.Client
	}
)

func NewBllPromptService(cli zrpc.Client) BllPromptService {
	return &defaultBllPromptService{
		cli: cli,
	}
}

// 占位方法，后续添加具体实现
func (m *defaultBllPromptService) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	client := bll_prompt.NewBllPromptServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
