// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "jxzy/apis/api_chat/internal/handler/chat"
	"jxzy/apis/api_chat/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cors},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chat/stream",
					Handler: chat.StreamChatHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
