// Code generated by goctl. DO NOT EDIT.
// Source: bllknowledge.proto

package server

import (
	"context"

	"jxzy/bll/bll_knowledge/bll_knowledge"
	"jxzy/bll/bll_knowledge/internal/logic"
	"jxzy/bll/bll_knowledge/internal/svc"
)

type BllKnowledgeServiceServer struct {
	svcCtx *svc.ServiceContext
	bll_knowledge.UnimplementedBllKnowledgeServiceServer
}

func NewBllKnowledgeServiceServer(svcCtx *svc.ServiceContext) *BllKnowledgeServiceServer {
	return &BllKnowledgeServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加知识库到向量数据库
func (s *BllKnowledgeServiceServer) AddVectorKnowledge(ctx context.Context, in *bll_knowledge.AddVectorKnowledgeRequest) (*bll_knowledge.AddVectorKnowledgeResponse, error) {
	l := logic.NewAddVectorKnowledgeLogic(ctx, s.svcCtx)
	return l.AddVectorKnowledge(in)
}

// 从向量数据库删除知识库
func (s *BllKnowledgeServiceServer) DeleteVectorKnowledge(ctx context.Context, in *bll_knowledge.DeleteVectorKnowledgeRequest) (*bll_knowledge.DeleteVectorKnowledgeResponse, error) {
	l := logic.NewDeleteVectorKnowledgeLogic(ctx, s.svcCtx)
	return l.DeleteVectorKnowledge(in)
}
