// Code generated by goctl. DO NOT EDIT.
// Source: bllknowledge.proto

package server

import (
	"context"

	"jxzy/bll/bll_knowledge/bll_knowledge"
	"jxzy/bll/bll_knowledge/internal/logic"
	"jxzy/bll/bll_knowledge/internal/svc"
)

type BllKnowledgeServiceServer struct {
	svcCtx *svc.ServiceContext
	bll_knowledge.UnimplementedBllKnowledgeServiceServer
}

func NewBllKnowledgeServiceServer(svcCtx *svc.ServiceContext) *BllKnowledgeServiceServer {
	return &BllKnowledgeServiceServer{
		svcCtx: svcCtx,
	}
}

// 占位方法，后续添加具体实现
func (s *BllKnowledgeServiceServer) Ping(ctx context.Context, in *bll_knowledge.Empty) (*bll_knowledge.Pong, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
