// Code generated by goctl. DO NOT EDIT.
package types

type AddKnowledgeRequest struct {
	Summary string `json:"summary"` // 知识库总结，用于向量化
	Content string `json:"content"` // 知识库内容
	UserId  string `json:"user_id"` // 用户ID
}

type AddKnowledgeResponse struct {
	VectorId string `json:"vector_id"` // 向量ID
	Success  bool   `json:"success"`   // 是否成功
	Message  string `json:"message"`   // 响应消息
}

type DeleteKnowledgeRequest struct {
	VectorId string `json:"vector_id"` // 向量ID
	UserId   string `json:"user_id"`   // 用户ID
}

type DeleteKnowledgeResponse struct {
	Success bool   `json:"success"` // 是否成功
	Message string `json:"message"` // 响应消息
}
