// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: bllknowledge.proto

package bll_knowledge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddVectorKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileUrl string `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"` // 知识文件的OSS地址
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
}

func (x *AddVectorKnowledgeRequest) Reset() {
	*x = AddVectorKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bllknowledge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVectorKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorKnowledgeRequest) ProtoMessage() {}

func (x *AddVectorKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bllknowledge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*AddVectorKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_bllknowledge_proto_rawDescGZIP(), []int{0}
}

func (x *AddVectorKnowledgeRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *AddVectorKnowledgeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddVectorKnowledgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorId string `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"` // 向量ID（summary和content的MD5）
	Success  bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                  // 操作是否成功
	Message  string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                   // 响应消息
}

func (x *AddVectorKnowledgeResponse) Reset() {
	*x = AddVectorKnowledgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bllknowledge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVectorKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorKnowledgeResponse) ProtoMessage() {}

func (x *AddVectorKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bllknowledge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*AddVectorKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_bllknowledge_proto_rawDescGZIP(), []int{1}
}

func (x *AddVectorKnowledgeResponse) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *AddVectorKnowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddVectorKnowledgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteVectorKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorId string `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"` // 向量ID
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
}

func (x *DeleteVectorKnowledgeRequest) Reset() {
	*x = DeleteVectorKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bllknowledge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVectorKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorKnowledgeRequest) ProtoMessage() {}

func (x *DeleteVectorKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bllknowledge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_bllknowledge_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteVectorKnowledgeRequest) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *DeleteVectorKnowledgeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteVectorKnowledgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 操作是否成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
}

func (x *DeleteVectorKnowledgeResponse) Reset() {
	*x = DeleteVectorKnowledgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bllknowledge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVectorKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorKnowledgeResponse) ProtoMessage() {}

func (x *DeleteVectorKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bllknowledge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVectorKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_bllknowledge_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVectorKnowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVectorKnowledgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bllknowledge_proto protoreflect.FileDescriptor

var file_bllknowledge_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6c, 0x6c, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x6c, 0x6c, 0x5f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x22, 0x4f, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x1d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xf4,
	0x01, 0x0a, 0x13, 0x42, 0x6c, 0x6c, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x62,
	0x6c, 0x6c, 0x5f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x6c, 0x6c, 0x5f, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x72, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x2b, 0x2e, 0x62, 0x6c, 0x6c,
	0x5f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x62, 0x6c, 0x6c, 0x5f, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x62, 0x6c, 0x6c, 0x5f, 0x6b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bllknowledge_proto_rawDescOnce sync.Once
	file_bllknowledge_proto_rawDescData = file_bllknowledge_proto_rawDesc
)

func file_bllknowledge_proto_rawDescGZIP() []byte {
	file_bllknowledge_proto_rawDescOnce.Do(func() {
		file_bllknowledge_proto_rawDescData = protoimpl.X.CompressGZIP(file_bllknowledge_proto_rawDescData)
	})
	return file_bllknowledge_proto_rawDescData
}

var file_bllknowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bllknowledge_proto_goTypes = []interface{}{
	(*AddVectorKnowledgeRequest)(nil),     // 0: bll_knowledge.AddVectorKnowledgeRequest
	(*AddVectorKnowledgeResponse)(nil),    // 1: bll_knowledge.AddVectorKnowledgeResponse
	(*DeleteVectorKnowledgeRequest)(nil),  // 2: bll_knowledge.DeleteVectorKnowledgeRequest
	(*DeleteVectorKnowledgeResponse)(nil), // 3: bll_knowledge.DeleteVectorKnowledgeResponse
}
var file_bllknowledge_proto_depIdxs = []int32{
	0, // 0: bll_knowledge.BllKnowledgeService.AddVectorKnowledge:input_type -> bll_knowledge.AddVectorKnowledgeRequest
	2, // 1: bll_knowledge.BllKnowledgeService.DeleteVectorKnowledge:input_type -> bll_knowledge.DeleteVectorKnowledgeRequest
	1, // 2: bll_knowledge.BllKnowledgeService.AddVectorKnowledge:output_type -> bll_knowledge.AddVectorKnowledgeResponse
	3, // 3: bll_knowledge.BllKnowledgeService.DeleteVectorKnowledge:output_type -> bll_knowledge.DeleteVectorKnowledgeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bllknowledge_proto_init() }
func file_bllknowledge_proto_init() {
	if File_bllknowledge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bllknowledge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVectorKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bllknowledge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVectorKnowledgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bllknowledge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVectorKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bllknowledge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVectorKnowledgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bllknowledge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bllknowledge_proto_goTypes,
		DependencyIndexes: file_bllknowledge_proto_depIdxs,
		MessageInfos:      file_bllknowledge_proto_msgTypes,
	}.Build()
	File_bllknowledge_proto = out.File
	file_bllknowledge_proto_rawDesc = nil
	file_bllknowledge_proto_goTypes = nil
	file_bllknowledge_proto_depIdxs = nil
}
