// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	embeddingSceneFieldNames          = builder.RawFieldNames(&EmbeddingScene{})
	embeddingSceneRows                = strings.Join(embeddingSceneFieldNames, ",")
	embeddingSceneRowsExpectAutoSet   = strings.Join(stringx.Remove(embeddingSceneFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	embeddingSceneRowsWithPlaceHolder = strings.Join(stringx.Remove(embeddingSceneFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	embeddingSceneModel interface {
		Insert(ctx context.Context, data *EmbeddingScene) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EmbeddingScene, error)
		FindOneBySceneCode(ctx context.Context, sceneCode string) (*EmbeddingScene, error)
		Update(ctx context.Context, data *EmbeddingScene) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEmbeddingSceneModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EmbeddingScene struct {
		Id              int64     `db:"id"`
		SceneCode       string    `db:"scene_code"`
		SceneName       string    `db:"scene_name"`
		ProviderCode    string    `db:"provider_code"`
		ProviderName    string    `db:"provider_name"`
		ModelCode       string    `db:"model_code"`
		ModelName       string    `db:"model_name"`
		VectorDimension int64     `db:"vector_dimension"`
		CollectionName  string    `db:"collection_name"`
		Deleted         int64     `db:"deleted"`
		CreatedAt       time.Time `db:"created_at"`
		UpdatedAt       time.Time `db:"updated_at"`
	}
)

func newEmbeddingSceneModel(conn sqlx.SqlConn) *defaultEmbeddingSceneModel {
	return &defaultEmbeddingSceneModel{
		conn:  conn,
		table: "`embedding_scene`",
	}
}

func (m *defaultEmbeddingSceneModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEmbeddingSceneModel) FindOne(ctx context.Context, id int64) (*EmbeddingScene, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", embeddingSceneRows, m.table)
	var resp EmbeddingScene
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmbeddingSceneModel) FindOneBySceneCode(ctx context.Context, sceneCode string) (*EmbeddingScene, error) {
	var resp EmbeddingScene
	query := fmt.Sprintf("select %s from %s where `scene_code` = ? and `deleted` = 0 limit 1", embeddingSceneRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, sceneCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmbeddingSceneModel) Insert(ctx context.Context, data *EmbeddingScene) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, embeddingSceneRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SceneCode, data.SceneName, data.ProviderCode, data.ProviderName, data.ModelCode, data.ModelName, data.VectorDimension, data.CollectionName, data.Deleted)
	return ret, err
}

func (m *defaultEmbeddingSceneModel) Update(ctx context.Context, newData *EmbeddingScene) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, embeddingSceneRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SceneCode, newData.SceneName, newData.ProviderCode, newData.ProviderName, newData.ModelCode, newData.ModelName, newData.VectorDimension, newData.CollectionName, newData.Deleted, newData.Id)
	return err
}

func (m *defaultEmbeddingSceneModel) tableName() string {
	return m.table
}

