// Code generated by goctl. DO NOT EDIT.
package types

type ChatRequest struct {
	UserId    string `json:"user_id"`             // 用户ID
	Message   string `json:"message"`             // 用户消息内容
	SessionId string `json:"session_id,optional"` // 会话ID，为空时自动创建
	SceneCode string `json:"scene_code"`          // 业务场景编码，必填
}

type StreamChatData struct {
	SessionId string      `json:"session_id"`     // 会话ID
	SceneCode string      `json:"scene_code"`     // 场景编码
	Delta     string      `json:"delta"`          // 增量内容
	Finished  bool        `json:"finished"`       // 是否结束
	Usage     *TokenUsage `json:"usage,optional"` // token使用情况(仅在finished=true时返回)
}

type TokenUsage struct {
	PromptTokens int64 `json:"prompt_tokens"` // 输入token数
	ReplyTokens  int64 `json:"reply_tokens"`  // 输出token数
	TotalTokens  int64 `json:"total_tokens"`  // 总token数
}
