// Code generated by goctl. DO NOT EDIT.
// Source: bllcontext.proto

package server

import (
	"jxzy/bll/bll_context/bll_context"
	"jxzy/bll/bll_context/internal/logic"
	"jxzy/bll/bll_context/internal/svc"
)

type BllContextServiceServer struct {
	svcCtx *svc.ServiceContext
	bll_context.UnimplementedBllContextServiceServer
}

func NewBllContextServiceServer(svcCtx *svc.ServiceContext) *BllContextServiceServer {
	return &BllContextServiceServer{
		svcCtx: svcCtx,
	}
}

// 流式聊天接口
func (s *BllContextServiceServer) StreamChat(in *bll_context.ChatRequest, stream bll_context.BllContextService_StreamChatServer) error {
	l := logic.NewStreamChatLogic(stream.Context(), s.svcCtx)
	return l.StreamChat(in, stream)
}
