// Code generated by goctl. DO NOT EDIT.
// Source: bllprompt.proto

package server

import (
	"context"

	"jxzy/bll/bll_prompt/bll_prompt"
	"jxzy/bll/bll_prompt/internal/logic"
	"jxzy/bll/bll_prompt/internal/svc"
)

type BllPromptServiceServer struct {
	svcCtx *svc.ServiceContext
	bll_prompt.UnimplementedBllPromptServiceServer
}

func NewBllPromptServiceServer(svcCtx *svc.ServiceContext) *BllPromptServiceServer {
	return &BllPromptServiceServer{
		svcCtx: svcCtx,
	}
}

// 占位方法，后续添加具体实现
func (s *BllPromptServiceServer) Ping(ctx context.Context, in *bll_prompt.Empty) (*bll_prompt.Pong, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
